spring.application.name=forex
spring.profiles.active=local

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:fxratedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Bundesbank API Configuration
bundesbank.api.base-url=https://api.statistiken.bundesbank.de/rest/data/BBEX3
bundesbank.api.endpoint.all-currencies=D..EUR.BB.AC.000
bundesbank.api.format=sdmx_csv
bundesbank.api.language=en
bundesbank.api.default-observations=100

# Scheduler Configuration
scheduler.exchange-rate.cron=0 0 6 * * ?

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.show-actuator=false
springdoc.packages-to-scan=com.crewmeister.forex.controller
springdoc.paths-to-exclude=/error