-- Insert all currencies (29 currencies from Bundesbank API)
INSERT INTO currencies (code, numeric_code, name, symbol, country_code, country_name, decimals, rounding, symbol_position, decimal_separator, is_active, created_at, updated_at, created_by, updated_by) VALUES
('EUR', '978', 'Euro', '€', 'EU', 'European Union', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('USD', '840', 'United States Dollar', '$', 'USA', 'United States', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('GBP', '826', 'British Pound Sterling', '£', 'GBR', 'United Kingdom', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('JPY', '392', 'Japanese Yen', '¥', 'JPN', 'Japan', 0, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('CHF', '756', 'Swiss Franc', 'CHF', 'CHE', 'Switzerland', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('AUD', '036', 'Australian Dollar', 'A$', 'AUS', 'Australia', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('CAD', '124', 'Canadian Dollar', 'C$', 'CAN', 'Canada', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('CNY', '156', 'Chinese Yuan', '¥', 'CHN', 'China', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('INR', '356', 'Indian Rupee', '₹', 'IND', 'India', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('BRL', '986', 'Brazilian Real', 'R$', 'BRA', 'Brazil', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('CZK', '203', 'Czech Koruna', 'Kč', 'CZE', 'Czech Republic', 2, 0, 'after', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('DKK', '208', 'Danish Krone', 'kr', 'DNK', 'Denmark', 2, 0, 'after', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('HKD', '344', 'Hong Kong Dollar', 'HK$', 'HKG', 'Hong Kong', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('HUF', '348', 'Hungarian Forint', 'Ft', 'HUN', 'Hungary', 2, 0, 'after', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('IDR', '360', 'Indonesian Rupiah', 'Rp', 'IDN', 'Indonesia', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('ILS', '376', 'Israeli New Shekel', '₪', 'ISR', 'Israel', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('ISK', '352', 'Icelandic Króna', 'kr', 'ISL', 'Iceland', 0, 0, 'after', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('KRW', '410', 'South Korean Won', '₩', 'KOR', 'South Korea', 0, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('MXN', '484', 'Mexican Peso', '$', 'MEX', 'Mexico', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('MYR', '458', 'Malaysian Ringgit', 'RM', 'MYS', 'Malaysia', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('NOK', '578', 'Norwegian Krone', 'kr', 'NOR', 'Norway', 2, 0, 'after', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('NZD', '554', 'New Zealand Dollar', 'NZ$', 'NZL', 'New Zealand', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('PHP', '608', 'Philippine Peso', '₱', 'PHL', 'Philippines', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('PLN', '985', 'Polish Złoty', 'zł', 'POL', 'Poland', 2, 0, 'after', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('RON', '946', 'Romanian Leu', 'lei', 'ROU', 'Romania', 2, 0, 'after', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('SEK', '752', 'Swedish Krona', 'kr', 'SWE', 'Sweden', 2, 0, 'after', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('SGD', '702', 'Singapore Dollar', 'S$', 'SGP', 'Singapore', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('THB', '764', 'Thai Baht', '฿', 'THA', 'Thailand', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('TRY', '949', 'Turkish Lira', '₺', 'TUR', 'Turkey', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
('ZAR', '710', 'South African Rand', 'R', 'ZAF', 'South Africa', 2, 0, 'before', '.', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system');
